#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2014-2016
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

language: c

compiler:
  - gcc

sudo: required
dist: trusty

# Remove bogus python installations from PATH,
# see https://github.com/travis-ci/travis-ci/issues/5326
before_install:
  - export PATH=$(echo $PATH | sed 's/\/opt\/python[^:]*//g')

install:
  # Install additional packages
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu wily main'
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-mako gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make
  # Install kernel build environment
  - pushd ci
  - wget -q http://www.kiszka.org/downloads/travis-ci/kernel-build.tar.xz
  - tar xJf kernel-build.tar.xz
  - popd

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ];
        then ci/build-all-configs.sh;
    fi

addons:
  coverity_scan:
    project:
      name: "siemens/jailhouse"
    notification_email: jan.kiszka@siemens.com
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/ci/coverity-scan-build.sh
    build_command_prepend: "cov-configure --comptype gcc --compiler arm-linux-gnueabihf-gcc --template"
    build_command: "unused"
    branch_pattern: coverity_scan.*
